Repository DoTheZ-Team/glue-fe, pull requests merged in 2024-06, with the labels that each got.

#55 GLUE-363-CICD-파이프라인-구축
  .github/workflows/glue-client.yml
  Dockerfile
  next.config.mjs
Labels: enhancement, feature

#53 GLUE-360-글작성-스티커-api-구현
  src/app/(publish)/components/PostEditor/index.tsx
  src/app/(publish)/store/index.ts
  src/app/blog/[blogId]/post/[postId]/components/PostDetailFetcher/types.ts
  src/app/blog/[blogId]/post/[postId]/components/PostDetailHeader/hooks/index.ts
  src/app/blog/[blogId]/post/[postId]/components/StickerRenderer/index.tsx
  src/app/blog/[blogId]/post/[postId]/page.tsx
Labels: feature

#59 GLUE-339-스티커-요청-api-연결
  next.config.mjs
  src/app/(auth)/auth/api/queries.ts
  src/app/(publish)/components/StickerFetcher/StickerContext.tsx
  src/app/(publish)/components/StickerFetcher/api.ts
  src/app/(publish)/components/StickerFetcher/hooks/index.ts
  src/app/(publish)/components/StickerFetcher/index.tsx
  src/app/(publish)/components/StickerFetcher/quries.ts
  src/app/(publish)/components/StickerPannel/api/index.ts
  src/app/(publish)/components/StickerPannel/components/StickerPannelRenderer/index.tsx
  src/app/(publish)/components/StickerPannel/hooks/useStickerPannel.ts
  src/app/(publish)/components/StickerPannel/index.tsx
  src/app/(publish)/hooks/useWritePost.ts
  src/app/blog/[blogId]/post/[postId]/components/CommentsWrapper/api/types.ts
  src/app/blog/[blogId]/post/[postId]/components/PostDetailFetcher/api/index.ts
  src/app/blog/[blogId]/post/[postId]/components/PostDetailFetcher/api/quries.ts
  src/app/blog/[blogId]/post/[postId]/components/PostDetailFetcher/index.tsx
  src/app/match/components/RecommendationFetcher/api/index.ts
  src/app/match/components/RecommendationFetcher/api/quries.ts
  src/app/match/components/RecommendationFetcher/index.tsx
  src/hooks/index.tsx
  src/hooks/useIntersect.ts
Labels: feature

#61 GLUE-369-private-경로-제한
  src/api/core.ts
  src/middleware.ts
Labels: enhancement, feature

#50 GLUE-238-마이페이지-api-연결
  package-lock.json
  public/images/profile.jpeg
  src/api/api.ts
  src/api/index.ts
  src/app/mypage/[blogId]/components/Background/index.tsx
  src/app/mypage/[blogId]/components/BlogInfo/index.tsx
  src/app/mypage/[blogId]/components/Common/FileThumbnails.tsx
  src/app/mypage/[blogId]/components/Common/index.tsx
  src/app/mypage/[blogId]/components/Common/useReadFile.tsx
  src/app/mypage/[blogId]/components/MyPageFallback/index.tsx
  src/app/mypage/[blogId]/components/MyPageFetcher/MyPageContext/MyPageProviderWrapper.tsx
  src/app/mypage/[blogId]/components/MyPageFetcher/MyPageContext/index.tsx
  src/app/mypage/[blogId]/components/MyPageFetcher/api.ts
  src/app/mypage/[blogId]/components/MyPageFetcher/index.tsx
  src/app/mypage/[blogId]/components/MyPageFetcher/queries.ts
  src/app/mypage/[blogId]/components/MyPageFetcher/types.ts
  src/app/mypage/[blogId]/components/Profile/index.tsx
  src/app/mypage/[blogId]/components/Title/index.tsx
  src/app/mypage/[blogId]/components/hooks/index.tsx
  src/app/mypage/[blogId]/components/hooks/useEdit.tsx
  src/app/mypage/[blogId]/components/hooks/useSave.tsx
  src/app/mypage/[blogId]/layout.tsx
  src/app/mypage/[blogId]/page.tsx
  src/app/mypage/components/Background/index.tsx
  src/app/mypage/components/BlogName/index.tsx
  src/app/mypage/components/Common/FileThumbnails.tsx
  src/app/mypage/layout.tsx
  src/app/mypage/page.tsx
  src/components/Common/FileEdit/index.tsx
  src/components/Common/index.tsx
Labels: feature

#63 GLUE-367-글작성-스티커-포함-api-연결
  src/api/core.ts
  src/app/(publish)/(route)/write/page.tsx
  src/app/(publish)/api/index.ts
  src/app/(publish)/api/queries.tsx
  src/app/(publish)/components/Konva/hooks/index.ts
  src/app/(publish)/components/Konva/index.tsx
  src/app/(publish)/components/PostEditor/index.tsx
  src/app/(publish)/components/Sticker/index.tsx
  src/app/(publish)/components/Sticker/types.ts
  src/app/(publish)/components/StickerPannel/api/quries.ts
  src/app/(publish)/components/StickerPannel/api/quries.tsx
  src/app/(publish)/components/StickerPannel/components/StickerPannelRenderer/index.tsx
  src/app/(publish)/components/StickerPannel/hooks/useStickerPannel.ts
  src/app/(publish)/hooks/useWritePost.ts
  src/app/blog/[blogId]/post/[postId]/components/CommentsWrapper/Comments/index.tsx
  src/app/blog/[blogId]/post/[postId]/components/PostDetailFetcher/types.ts
  src/app/blog/[blogId]/post/[postId]/components/StickerRenderer/index.tsx
  src/app/blog/[blogId]/post/[postId]/page.tsx
Labels: enhancement, feature

#64 GLUE-376-불필요한-코드-삭제
  src/app/(auth)/auth/page.tsx
  src/components/Common/NavigationIcons/index.tsx
Labels: bug

#65 GLUE-377-매칭-버튼-추가
  src/app/(auth)/auth/api/queries.ts
  src/app/(publish)/api/index.ts
  src/app/(publish)/api/queries.tsx
  src/components/MouseImageGallery/index.tsx
Labels: enhancement, feature

#67 GLUE-380-image의-remotePatterns-추가
  next.config.mjs
Labels: bug

#66 Glue-258-검색페이지-api-연결
  src/api/types.ts
  src/app/lib/dummyData.js
  src/app/search/components/BlogList/BlogCard.tsx
  src/app/search/components/BlogList/index.tsx
  src/app/search/components/ContentList/index.tsx
  src/app/search/components/SearchBox/index.tsx
  src/app/search/components/SearchFallback/index.tsx
  src/app/search/components/SearchFetcher/SearchContext.tsx
  src/app/search/components/SearchFetcher/api.ts
  src/app/search/components/SearchFetcher/index.tsx
  src/app/search/components/SearchFetcher/quries.ts
  src/app/search/components/SearchFetcher/types.ts
  src/app/search/layout.tsx
  src/app/search/page.tsx
  src/app/subscribe/components/Pagination/index.tsx
  src/app/subscribe/components/SubscribeFetcher/types.ts
  src/components/Common/NavigationIcons/index.tsx
  src/hooks/index.tsx
  src/hooks/useSearch.tsx
Labels: feature

#73 GLUE 378 이미지 첨부 api 연결
  src/api/api.ts
  src/api/index.ts
  src/components/Common/Editor/hooks/index.tsx
  src/components/Common/FileEdit/index.tsx
Labels: enhancement, feature

#76 GLUE 386 이미지 로딩을 위한 config 수정
  next.config.mjs
  src/app/(publish)/components/StickerFetcher/hooks/index.ts
  src/app/(publish)/components/StickerPannel/index.tsx
  src/app/(publish)/constants/dummyIcons/Ghost.tsx
  src/app/(publish)/constants/dummyIcons/Github.tsx
  src/app/(publish)/constants/dummyIcons/Smile.tsx
  src/app/(publish)/constants/dummyIcons/Star.tsx
  src/app/(publish)/constants/dummyIcons/index.tsx
Labels: bug

#77 GLUE-386 오타 수정
  next.config.mjs
Labels: bug

#78 GLUE-378 이미지 주소 수정
  next.config.mjs
Labels: bug

#79 GLUE-386 next.config 수정
  next.config.mjs
Labels: bug

#80 GLUE-387 next.config 설정 추가
  next.config.mjs
Labels: bug

#82 GLUE-387 이미지 로딩을 위해 Image 태그의 loader 추가
  next.config.mjs
  src/app/(publish)/components/PostEditor/index.tsx
  src/app/(publish)/components/StickerPannel/components/StickerPannelRenderer/index.tsx
  src/components/Common/Dropdown/index.tsx
Labels: bug

#83 fix: nextjs Image 태그에 loader 추가
  src/app/blog/[blogId]/post/[postId]/components/StickerRenderer/index.tsx
Labels: bug

#81 GLUE-201-게시판-구현
  src/app/blog/[blogId]/components/Albums/Slider.tsx
  src/app/blog/[blogId]/components/Albums/index.tsx
  src/app/blog/[blogId]/components/BlogBackground/index.tsx
  src/app/blog/[blogId]/components/BlogFetcher/BlogContext.tsx
  src/app/blog/[blogId]/components/BlogFetcher/api.ts
  src/app/blog/[blogId]/components/BlogFetcher/index.tsx
  src/app/blog/[blogId]/components/BlogFetcher/queries.ts
  src/app/blog/[blogId]/components/BlogFetcher/types.ts
  src/app/blog/[blogId]/components/BlogHeader/index.tsx
  src/app/blog/[blogId]/components/Board/BoardContent.tsx
  src/app/blog/[blogId]/components/Board/index.tsx
  src/app/blog/[blogId]/components/ProfileBox/index.tsx
  src/app/blog/[blogId]/components/StoryBox/index.tsx
  src/app/blog/[blogId]/components/SubscriptionButton/api/index.ts
  src/app/blog/[blogId]/components/SubscriptionButton/api/queries.ts
  src/app/blog/[blogId]/components/SubscriptionButton/index.tsx
  src/app/blog/[blogId]/components/Tags/index.tsx
  src/app/blog/[blogId]/components/index.tsx
  src/app/blog/[blogId]/page.tsx
  src/app/mypage/[blogId]/layout.tsx
  src/app/mypage/[blogId]/page.tsx
  src/app/mypage/components/Background/index.tsx
  src/app/mypage/components/BlogInfo/index.tsx
  src/app/mypage/components/Common/FileThumbnails.tsx
  src/app/mypage/components/Common/index.tsx
  src/app/mypage/components/Common/useReadFile.tsx
  src/app/mypage/components/MyPageFallback/index.tsx
  src/app/mypage/components/MyPageFetcher/MyPageContext/MyPageProviderWrapper.tsx
  src/app/mypage/components/MyPageFetcher/MyPageContext/index.tsx
  src/app/mypage/components/MyPageFetcher/api.ts
  src/app/mypage/components/MyPageFetcher/index.tsx
  src/app/mypage/components/MyPageFetcher/queries.ts
  src/app/mypage/components/MyPageFetcher/types.ts
  src/app/mypage/components/Profile/index.tsx
  src/app/mypage/components/Title/index.tsx
  src/app/mypage/components/hooks/index.tsx
  src/app/mypage/components/hooks/useEdit.tsx
  src/app/mypage/components/hooks/useSave.tsx
  src/app/mypage/layout.tsx
  src/app/mypage/page.tsx
  src/components/Common/FileEdit/index.tsx
  src/components/Common/UserContext/UserProviderWrapper.tsx
  src/components/Common/UserContext/index.tsx
Labels: feature

#84 Glue 381 qa 수정
  src/api/core.ts
  src/app/(publish)/components/PostEditor/index.tsx
  src/app/blog/[blogId]/components/Albums/Slider.tsx
  src/app/blog/[blogId]/components/BlogBackground/index.tsx
  src/app/blog/[blogId]/components/Board/BoardContent.tsx
  src/app/blog/[blogId]/components/ProfileBox/index.tsx
  src/app/blog/[blogId]/post/[postId]/components/CommentsWrapper/Comments/ChildComments/ChildComments.tsx
  src/app/blog/[blogId]/post/[postId]/components/CommentsWrapper/Comments/Comment.tsx
  src/app/blog/[blogId]/post/[postId]/components/CommentsWrapper/index.tsx
  src/app/blog/[blogId]/post/[postId]/components/PostDetailFetcher/types.ts
  src/app/blog/[blogId]/post/[postId]/components/PostDetailHeader/index.tsx
  src/app/blog/[blogId]/post/[postId]/page.tsx
  src/app/match/page.tsx
  src/app/mypage/components/Common/FileThumbnails.tsx
  src/app/search/components/BlogList/BlogCard.tsx
  src/app/subscribe/components/FeedBox/index.tsx
  src/components/Common/Icons/Mypage.tsx
  src/components/Common/Icons/index.tsx
  src/components/MouseImageGallery/index.tsx
Labels: bug

#86 GLUE 381 복사 기능 구현
  src/app/(publish)/hooks/useWritePost.ts
  src/app/blog/[blogId]/post/[postId]/components/PostDetailHeader/hooks/index.ts
  src/app/blog/[blogId]/post/[postId]/components/PostDetailHeader/index.tsx
  src/utils/common/Clipboard.ts
  src/utils/common/Device.ts
  src/utils/common/index.ts
Labels: feature

#88 GLUE-383 프로필 사용자 이미지 API 연결
  src/app/blog/[blogId]/post/[postId]/components/PostDetailFetcher/types.ts
  src/app/blog/[blogId]/post/[postId]/components/PostDetailHeader/index.tsx
Labels: feature

#91 GLUE-303 로그인 아이디를 쿠키에서 활용할 수 있도록 수정
  src/app/(auth)/auth/api/queries.ts
  src/app/mypage/components/MyPageFetcher/MyPageContext/MyPageProviderWrapper.tsx
  src/app/mypage/components/MyPageFetcher/MyPageContext/index.tsx
  src/app/mypage/components/MyPageFetcher/index.tsx
  src/app/mypage/components/MyPageFetcher/queries.ts
  src/app/mypage/components/hooks/useSave.tsx
  src/app/mypage/page.tsx
  src/constants/api.ts
Labels: bug

#94 GLUE 304 QA 반영
  src/app/blog/[blogId]/components/Albums/Slider.tsx
  src/app/blog/[blogId]/components/Albums/index.tsx
  src/app/blog/[blogId]/components/BlogFetcher/types.ts
  src/app/blog/[blogId]/components/Board/index.tsx
  src/app/blog/[blogId]/components/StoryBox/index.tsx
  src/app/blog/[blogId]/page.tsx
  src/app/blog/[blogId]/post/[postId]/components/PostDetailHeader/index.tsx
  src/app/search/components/BlogList/index.tsx
  src/app/subscribe/components/Feed/FeedContent.tsx
  src/app/subscribe/components/SubscribeFetcher/types.ts
  src/components/Common/Pagination/usePagination.ts
  src/components/MouseImageGallery/index.tsx
Labels: bug
